//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recetas_y_Mascotas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascotas
    {
        public int Id { get; set; }
        public string Nombre_Mascota { get; set; }
        public string Color { get; set; }
        public string Raza { get; set; }
        public string Edad { get; set; }
        public string Sexo { get; set; }
        public string Nombre_Dueño { get; set; }
        public string Telefono { get; set; }
    }
}
